### ISSUE TITLE
Ошибка: Нарушен принцип инкапсуляции

### ISSUE THREAD

**Issue by zloiia** [zloiia-edu/dz-1-parser-logov-igor317#1]
https://github.com/zloiia-edu/dz-1-parser-logov-igor317/blob/e4bf7bd35c3b51ffd6c84a98c8594bf13bd3b65e/1.cpp#L174

Свойство класса стало публичным. Нарушается принцип инкапсуляции.

**Comment by igor317** [comment]
Точно. изменил на приватный тип

**Comment by zloiia** [comment]
Ошибка устранена. Молодец.
