### ISSUE TITLE
Архитектурный недочет

### ISSUE THREAD

**Issue by zloiia** [zloiia-edu/dz-1-parser-logov-igor317#2]
https://github.com/zloiia-edu/dz-1-parser-logov-igor317/blob/e4bf7bd35c3b51ffd6c84a98c8594bf13bd3b65e/1.cpp#L174

Тут ты решаешь использовать для ввода данных из базы данных тот-же тип, что и для ввода-вывода  данных об ошибках, просто расширив интерфейс класса **FileIO** ( https://github.com/zloiia-edu/dz-1-parser-logov-igor317/blob/e4bf7bd35c3b51ffd6c84a98c8594bf13bd3b65e/1.cpp#L150 ), который архитектурно не предназначался для работы с базами данных. Таким образом получается, что классы, которые работают с потоком ошибок, получают возможность с ним взаимодействовать как с потоком базы данных. Отсюда может возникнуть ошибка, если, к примеру, пользователь класса **FileIO** откроет файл с ошибками и случайно обратится к методу **FoundMessage**. 

Попробуй пересмотреть архитектуру приложения для обхода этой проблемы.
Подсказка: создавать новые классы никто не запрещал.

**Comment by igor317** [comment]
Понял, создал дочерний класс FileIO для работы с базой данных. Я изначально хотел сделать класс для дб, однако подумал, что не стоит из-за одной функции делать целый класс и при этом повторять то, что уже есть.

**Comment by zloiia** [comment]
> что не стоит из-за одной функции делать целый класс и при этом повторять то, что уже есть.

В данном случае эти классы схожи только в том, что  оба они работают с файлом. Однако, в FileIO ты реализуешь интерфейс для работы с файлом ошибок или файлом вывода результатов, который обладает своей логикой. То есть когда мы работаем с классом FileIO, мы работаем с файлами, из которых мы вводим входные данные для обработки (в данном случае) и выводим их. то есть они обладают одним форматом. База данных ошибок, обладает совершенно другим форматом и подчиняется совсем другим правилам. Следовательно, для этого создать отдельный класс, который не наследует поведение других классов, совсем не зазорно. Исходи из контекста поставленной задачи всегда. 

Наследование от FileIO в твоем текущем решении не спасло ситуацию, так как у тебя при работе с файлом базы данных все равно остался интерфейс для работы с ним, как с потоком ошибок.

**Comment by igor317** [comment]
То есть если к классе есть методы, необходимые для работы с дб (открыть-закрыть файл), но при этом есть и методы, которые нельзя использовать при работе с ней, тогда стоит создать класс с нуля и продублировать нужные функции?

**Comment by zloiia** [comment]
> То есть если к классе есть методы, необходимые для работы с дб (открыть-закрыть файл), но при этом есть и методы, которые нельзя использовать при работе с ней, тогда стоит создать класс с нуля и продублировать нужные функции?

Да. Это стоит того, чтобы чтобы не предоставлять ненужные интерфейсы

**Comment by zloiia** [comment]
Решение мне нравится. Недочет закрываем.
